### ISSUE TITLE
Add assert construct to the Redex model

### ISSUE THREAD

**Issue by julbinb** [julbinb/juliette-wa#1]
For testing optimization correctness, it would be convenient to have `assert` in the calculus.
Then we'll be able to write tests such as:

```julia
g(x) = f(x) * 2
f(x) = x
@assert g(1+1) == 4
f(x) = -x
@assert g(1+1) == -4
```

**TODO:**

1. Extend Redex surface language and semantics

2. Extend Julia-to-Redex transpiler to support  `@assert <Expr>`

## Assert semantics

* Expressions `e ::= ... | (assert e)`

* Errors `err := ... | assert-err`

* Operational semantics
  - `(assert true) --> nothing`
  - `(assert false) --> assert-err`
  - `(assert v) where v is not boolean --> type-err`

**Comment by gelinasj** [comment]
Relevant Commits:
* 7f99a504eab11db085ec00327fd67e007699c37a
