### ISSUE TITLE
Convert opt litmus into runnable tests

### ISSUE THREAD

**Issue by julbinb** [julbinb/juliette-wa#2]
Convert [litmus tests](https://github.com/julbinb/juliette-wa/blob/master/litmus/optimizations.jl) for optimizations into separate runnable, jl-transpiled tests.

*Note.* Consider moving code for test generation from `tests` to `src`.

**Comment by gelinasj** [comment]
Relevant commits:
* 6547d1b884d651f4aa44b54720639ca32578b359
* 74780dd1fe130a4047e57ac1724d12262939126e
* 2ae4d8e42ca58414bf45781cd60b86b32b1c7968
* 9b076fb85bc60315c0b9338705c455bb4dc15a08
* 7f4ae0e9fea7e557af78abb836ac92330aab7857
